### ISSUE TITLE
Crash:java.lang.IndexOutOfBoundsException: replace (8 ... 12) ends beyond length 11

### ISSUE THREAD

**Issue by BongJaeChoi** [mabbas007/TagsEditText#39]
Hi
I'm using the features of TagsEditText well. Nice and good. I found one problem.

After typing several tags and clearing a few tags and typing again, tagging does not work properly with the following error. It's okay if you just type it, but it seems to be a problem if you delete it and retype it.

Please advice me. and fix it

Fatal Exception: java.lang.IndexOutOfBoundsException: replace (8 ... 12) ends beyond length 11
       at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1265)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:515)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
       at mabbas007.tagsedittext.TagsEditText.removeTagSpan(TagsEditText.java:570)
       at mabbas007.tagsedittext.TagsEditText.access$800(TagsEditText.java:51)
       at mabbas007.tagsedittext.TagsEditText$3.onClick(TagsEditText.java:557)
       at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:217)
       at android.widget.TextView.onTouchEvent(TextView.java:10059)
       at android.view.View.dispatchTouchEvent(View.java:10723)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.widget.ScrollView.dispatchTouchEvent(ScrollView.java:738)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:559)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1870)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3236)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
       at io.userhabit.service.main.b.g.dispatchTouchEvent(Unknown Source)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:521)
       at android.view.View.dispatchPointerEvent(View.java:10952)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5121)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4973)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4504)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4557)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4523)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4656)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4531)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4713)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4504)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4557)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4523)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4531)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4504)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7011)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6940)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6901)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7121)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by logesh45** [comment]
I have this issue too. @BongJaeChoi did you find a fix?
